### ISSUE TITLE
We should show 'View Notes' button on new muslim details screen even if there are no notes

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#70]
Seems like currently we are only showing this button when there are notes added for a new muslim otherwise this button is hidden. This gives a wrong impression, please show this button in all cases and if there are no meeting notes for a new muslim it should show that "there are no meeting notes"

**Comment by MuhammadSarimBader** [comment]
<img width="369" alt="Screen Shot 2020-07-23 at 8 55 29 AM" src="https://user-images.githubusercontent.com/31985211/88250853-4adde800-ccc2-11ea-89aa-ace7bcb94e20.png">

**Comment by MuhammadSarimBader** [comment]
meeting notes for Admin to new muslim is implemented as if the new muslim is active only then it will show meeting notes button. otherwise when user is inactive, unapproved and unclaimed it will not show meeting notes. For unapproved and unclaimed accounts it make sense, yea? and for inactive I show activate button instead. This is specifically iOS implementation. I tried not to have discrepancies between iOS and android so same would be in android. Also I will ask the QA and Devs to verify these behaviors in both iOS and android.

**Comment by MuhammadSarimBader** [comment]
meeting notes button will show always regardless of newMuslim status
